<div class="blog-post">
                <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
                <div class="hover-img">
                    <a rel="prettyPhoto" class="zoom fade-img" href="{dede:global.cfg_templets_skin/}/images/large_image.png" title="Title goes here"></a>
                    <a href="{dede:global.cfg_templets_skin/}/blog-single.html" class="fade-img"></a>
                    <img src="[field:picname/]" alt="[field:title/]">
                    <i style="opacity: 0;"></i>
                </div>
                <div class="post-text">
                    <a class="col1-12" href="[field:arcurl/]">
                        <span>20</span>
                        <span class="post-date">Dec</span>
                        <span class="num-comm">5</span>
                    </a>
                    <div class="post">
                        <p class="auth-cat">[field:writer/]</p>
                        <p>[field:infos/]</p>
                        <br>
                    </div>
                </div>
            </div>
            <div class="medium-bg-h3"></div>