<?php
$z[0]=Array("arcurl","",54,69);
$z[0][4]=array();
$z[1]=Array("title","",71,85);
$z[1][4]=array();
$z[2]=Array("arcurl","",182,197);
$z[2][4]=array();
$z[3]=Array("pubdate","",231,272);
$z[3][4]=array();
$z[3][4]['function']="date('d',@me)";
$z[4]=Array("pubdate","",328,369);
$z[4][4]=array();
$z[4][4]['function']="date('m',@me)";
$z[5]=Array("body","",471,512);
$z[5][4]=array();
$z[5][4]['function']="substr(@me,0,60)";

?>