<div class="blog-post">
                <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
                <div class="post-text">
                  
                    <div class="post">
                        <p class="auth-cat">[field:writer/]&ensp;<i style="font-size: 10px;">[field:pubdate function="date('Y-m-d',@me)"/]</i></p>
                        <p>[field:body function='substr(@me,0,60)'/]</p>
                        <br>
                    </div>
                </div>
            </div>
            <div class="medium-bg-h3"></div>