<div>
                    <img src="[field:picname/]" style="width: 100%;height: 100%;">
                    <div class="caption elemHover fromLeft">
                        <div class="caption-txt">
                            <h2>[field:title/]</h2>
                            <p>[field:infos/]</p>
                            <div><a href="[field:arcurl/]">详情</a></div>
                        </div>
                    </div>
                </div>