<div class="grid_3">
                <div class="home-portfolio">
                    <div class="hover-img">
                        <a rel="prettyPhoto" class="zoom fade-img" href=" [field:picname/]" title="Title goes here"></a>
                        <a href=" [field:arcurl/]" class="fade-img"></a>
                        <img src=" [field:picname/]" alt="Home Portfolio">
                        <i style="opacity: 0;"></i>
                    </div>
                    <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                    <div class="small-spacer"></div>
                    <p>[field:infos/]</p>
                </div>
            </div>