<div class="grid_9 intro-box sidebg upp-case">
            <h2>Welcome to Oreva Premium Theme</h2>
            <p>Nam nec dolor dui, id suscipit eros. Fusce dignissim bibendum lectus, in ornare tortor laoreet in. Donec sit amet arcu quis nibh consectetur vestibulum sed in diam. Proin quis neque risus, a dapibus lorem.</p>
        </div>
        {/dede}
        <div class="grid_3 social-icons upp-case">
            <h2>Find us on</h2>
            <div>Please click below icons for updates</div>
            <ul>
                <li><a href="{dede:global.cfg_templets_skin