<?php
$z[0]=Array("field","",88,110);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n            <div class=\"grid_3\">\r\n                <div class=\"home-portfolio\">\r\n                    <div class=\"hover-img\">\r\n                        <a rel=\"prettyPhoto\" class=\"zoom fade-img\" href=\" [field:picname/]\" title=\"Title goes here\"></a>\r\n                        <a href=\" [field:arcurl/]\" class=\"fade-img\"></a>\r\n                        <img src=\" [field:picname/]\" alt=\"Home Portfolio\">\r\n                        <i style=\"opacity: 0;\"></i>\r\n                    </div>\r\n                    <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n                    <div class=\"small-spacer\"></div>\r\n                    <p>[field:infos/]</p>\r\n                </div>\r\n            </div>\r\n            ",173,910);
$z[1][4]=array();

?>