<div>
                    <img src="[field:picname/]" style="width: 100%;height: 100%;">
                    <div class="caption elemHover fromLeft">
                        <div class="caption-txt">
                            <h2>[field:title/]</h2>
                            <p>[field:infos/]assssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss</p>
                            <div><a href="{dede:global.cfg_templets_skin/}/#">查看</a></div>
                        </div>
                    </div>
                </div>