<a href='[field:arcurl/]'>[field:title/]</a>
                <div>
                    <img src="[field:picname/]" style="width: 100%;height: 100%;">
                    <div class="caption elemHover fromLeft">
                        <div class="caption-txt">
                            <h2>[field:title]</h2>
                            <p>Nullam commodo imperdiet nulla in vulputate. Fusce in mauris quis massa fringilla consequat in eget elit. Suspendisse id est libero, vel ullamcorper dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            <div><a href="{dede:global.cfg_templets_skin/}/#">read more</a></div>
                        </div>
                    </div>
                </div>