<field:age itemname="年龄" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="3" page="">
</field:age>
<field:sex itemname="性别" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="男,女,保密"  maxlength="3" page="">
</field:sex>
<field:body itemname="详情" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:body>
