<div class="blog-post">
                <h2><a href="[field:title/]">[field:title/]</a></h2>
                <div class="hover-img">
                    <a rel="prettyPhoto" class="zoom fade-img" href="{dede:global.cfg_templets_skin/}/images/large_image.png" title="Title goes here"></a>
                    <a href="{dede:global.cfg_templets_skin/}/blog-single.html" class="fade-img"></a>
                    <img src="{dede:global.cfg_templets_skin/}/images/blogimg1_1col.png" alt="Home Portfolio">
                    <i style="opacity: 0;"></i>
                </div>
                <div class="post-text">
                    <a class="col1-12" href="{dede:global.cfg_templets_skin/}/blog-single.html">
                        <span>20</span>
                        <span class="post-date">Dec</span>
                        <span class="num-comm">5</span>
                    </a>
                    <div class="post">
                        <p class="auth-cat">Posted by <strong><a href="{dede:global.cfg_templets_skin/}/#">Oreva</a></strong> in <a class="clr-link" href="{dede:global.cfg_templets_skin/}/#">Landed</a><img alt="" src="{dede:global.cfg_templets_skin/}/images/comment_icon.png" class="ml-10"></p>
                        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam <a href="{dede:global.cfg_templets_skin/}/#">voluptatem quia voluptas</a> sit aspernatur[...]</p>
                    </div>
                </div>
            </div>
            <div class="medium-bg-h3"></div>