<?php
$z[0]=Array("arcurl","",54,69);
$z[0][4]=array();
$z[1]=Array("title","",71,85);
$z[1][4]=array();
$z[2]=Array("picname","",206,222);
$z[2][4]=array();
$z[3]=Array("arcurl","",283,298);
$z[3][4]=array();
$z[4]=Array("picname","",353,369);
$z[4][4]=array();
$z[5]=Array("title","",376,390);
$z[5][4]=array();
$z[6]=Array("arcurl","",553,568);
$z[6][4]=array();
$z[7]=Array("pubdate","",602,653);
$z[7][4]=array();
$z[7][4]['function']="date('Y-m-d h:i:s',@me)";
$z[8]=Array("writer","",889,904);
$z[8][4]=array();
$z[9]=Array("infos","",937,951);
$z[9][4]=array();

?>