<div class="blog-post">
                <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
                <div class="hover-img">
                    <a rel="prettyPhoto" class="zoom fade-img" href="[field:picname/]" title="Title goes here"></a>
                    <a href="[field:arcurl/]" class="fade-img"></a>
                    <img src="[field:picname/]" alt="[field:title/]">
                    <i style="opacity: 0;"></i>
                </div>
                <div class="post-text">
                    <a class="col1-12" href="[field:arcurl/]">
                        <span>[field:pubdate function="date('d',@me)"/]</span>
                        <span class="num-comm">[field:pubdate function="date('m',@me)"/]</span>
                    </a>
                    <div class="post">
                        <p class="auth-cat">[field:writer/]&ensp;<i style="font-size: 10px;">[field:pubdate function="date('Y-m-d',@me)"/]</i></p>
                        <p>[field:body function='substr(@me,0,60)'/]</p>
                        <br>
                    </div>
                </div>
            </div>
            <div class="medium-bg-h3"></div>