<?php
$z[0]=Array("global","",125,157);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",171,203);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",372,394);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",396,418);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",602,629);
$z[4][4]=array();
$z[4][4]['name']="cfg_indexurl";
$z[5]=Array("global","",631,659);
$z[5][4]=array();
$z[5][4]['name']="cfg_indexname";
$z[6]=Array("channel","\r\n                    <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n                    ",737,888);
$z[6][4]=array();
$z[6][4]['type']="top";
$z[6][4]['row']="8";

?>